name: ScafL

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-appimage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Set up appimage-builder
      run: |
        wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.0.0-beta.1/appimage-builder-1.0.0-677acbd-x86_64.AppImage
        chmod +x appimage-builder-x86_64.AppImage
    - name: Build AppImage
      run: |
        appimage-builder-x86_64.AppImage --recipe AppImageBuilder-apt.yml
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      env:
        SCAFL_VERSION: "$(python -c 'import src.scafl;print(src.scafl.__version__)')"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.SCAFL_VERSION }}"
        prerelease: false
        files: |
          LICENSE
          *.AppImage
          
